import Foundation
import os

private let logger = Logger(subsystem: "com.summarizecontent.app", category: "YouTubeCaptions")

// MARK: - Public Result

struct YouTubeCaptionResult {
    let segments: [TranscriptionSegment]
    let fullText: String
    let languageCode: String
    let isAutoGenerated: Bool
}

// MARK: - Service

struct YouTubeCaptionService {

    // MARK: - Video ID Extraction

    static func extractVideoID(from url: URL) -> String? {
        // youtu.be/VIDEO_ID
        if let host = url.host()?.lowercased(), host.contains("youtu.be") {
            let path = url.path().trimmingCharacters(in: CharacterSet(charactersIn: "/"))
            return path.isEmpty ? nil : path
        }

        // youtube.com/shorts/VIDEO_ID
        if url.absoluteString.contains("/shorts/") {
            let parts = url.pathComponents
            if let idx = parts.firstIndex(of: "shorts"), idx + 1 < parts.count {
                return parts[idx + 1]
            }
        }

        // youtube.com/watch?v=VIDEO_ID
        if let components = URLComponents(url: url, resolvingAgainstBaseURL: false),
           let vParam = components.queryItems?.first(where: { $0.name == "v" })?.value,
           !vParam.isEmpty {
            return vParam
        }

        return nil
    }

    // MARK: - Fetch Captions

    /// Fetch captions for a YouTube video. Returns nil when no captions are available
    /// (caller should fall back to Whisper).
    func fetchCaptions(from url: URL, preferredLanguage: String = "en") async -> YouTubeCaptionResult? {
        guard let videoID = Self.extractVideoID(from: url) else {
            logger.warning("Could not extract video ID from URL: \(url.absoluteString)")
            return nil
        }

        logger.notice("Fetching captions for video ID: \(videoID)")

        do {
            // 1. Use YouTube innertube API to get player response (avoids HTML parsing + consent pages)
            let tracks = try await fetchCaptionTracks(videoID: videoID, preferredLanguage: preferredLanguage)
            guard !tracks.isEmpty else {
                logger.notice("No caption tracks found for video \(videoID)")
                return nil
            }

            logger.notice("Found \(tracks.count) caption track(s)")

            // 2. Select best track: prefer manual over auto-generated, prefer requested language
            guard let track = selectBestTrack(tracks, preferredLanguage: preferredLanguage) else {
                return nil
            }

            logger.notice("Selected track: lang=\(track.languageCode), auto=\(track.kind ?? "manual")")

            // 3. Fetch JSON3 caption data
            let captionURLString = track.baseUrl + "&fmt=json3"
            guard let captionURL = URL(string: captionURLString) else { return nil }
            let (captionData, _) = try await URLSession.shared.data(from: captionURL)
            guard let json3 = try? JSONDecoder().decode(YouTubeCaptionJSON3.self, from: captionData) else {
                logger.warning("Failed to decode JSON3 caption data")
                return nil
            }

            // 4. Convert to TranscriptionSegments
            let segments = convertToSegments(json3)
            guard !segments.isEmpty else {
                logger.warning("JSON3 decoded but produced 0 segments")
                return nil
            }

            let fullText = segments.map(\.text).joined(separator: " ")
            let isAuto = track.kind == "asr"

            logger.notice("Caption fetch succeeded: \(segments.count) segments, \(fullText.count) chars, auto=\(isAuto)")

            return YouTubeCaptionResult(
                segments: segments,
                fullText: fullText,
                languageCode: track.languageCode,
                isAutoGenerated: isAuto
            )
        } catch {
            logger.error("Caption fetch failed: \(error.localizedDescription)")
            return nil
        }
    }

    // MARK: - Innertube API

    /// Fetch caption tracks using YouTube's innertube player API.
    /// This returns the player response directly as JSON — no HTML parsing needed.
    private func fetchCaptionTracks(videoID: String, preferredLanguage: String) async throws -> [CaptionTrack] {
        let apiURL = URL(string: "https://www.youtube.com/youtubei/v1/player?prettyPrint=false")!

        var request = URLRequest(url: apiURL)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
            forHTTPHeaderField: "User-Agent"
        )
        request.setValue("https://www.youtube.com", forHTTPHeaderField: "Origin")
        request.setValue("https://www.youtube.com/", forHTTPHeaderField: "Referer")

        let body: [String: Any] = [
            "videoId": videoID,
            "context": [
                "client": [
                    "clientName": "WEB",
                    "clientVersion": "2.20250101.00.00",
                    "hl": preferredLanguage
                ]
            ]
        ]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let (data, response) = try await URLSession.shared.data(for: request)

        if let httpResponse = response as? HTTPURLResponse {
            logger.notice("Innertube API response status: \(httpResponse.statusCode)")
        }

        let playerResponse = try JSONDecoder().decode(YouTubePlayerResponse.self, from: data)
        return playerResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? []
    }

    // MARK: - Track Selection

    /// Pick the best caption track: manual tracks preferred over auto-generated, then prefer the requested language.
    private func selectBestTrack(_ tracks: [CaptionTrack], preferredLanguage: String) -> CaptionTrack? {
        let manual = tracks.filter { $0.kind != "asr" }
        let auto = tracks.filter { $0.kind == "asr" }

        // Try manual in preferred language first
        if let match = manual.first(where: { $0.languageCode == preferredLanguage }) {
            return match
        }
        // Any manual track
        if let match = manual.first {
            return match
        }
        // Auto-generated in preferred language
        if let match = auto.first(where: { $0.languageCode == preferredLanguage }) {
            return match
        }
        // Any auto-generated
        return auto.first
    }

    // MARK: - JSON3 → TranscriptionSegment

    /// Convert JSON3 events into `TranscriptionSegment` array.
    private func convertToSegments(_ json3: YouTubeCaptionJSON3) -> [TranscriptionSegment] {
        guard let events = json3.events else { return [] }

        // Filter to events that have segment data (segs array)
        let captionEvents = events.filter { $0.segs != nil && !($0.segs?.isEmpty ?? true) }

        return captionEvents.compactMap { event in
            guard let segs = event.segs else { return nil }

            let startMs = event.tStartMs ?? 0
            let durationMs = event.dDurationMs ?? 0
            let startTime = Double(startMs) / 1000.0
            let endTime = Double(startMs + durationMs) / 1000.0

            // Build text from segments
            let text = segs.map { $0.utf8 ?? "" }.joined().trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { return nil }

            // Build word-level timing when offset data is available
            let words: [TranscriptionWord] = segs.compactMap { seg in
                guard let word = seg.utf8?.trimmingCharacters(in: .whitespacesAndNewlines),
                      !word.isEmpty else { return nil }

                let wordStartMs = startMs + (seg.tOffsetMs ?? 0)
                let wordStart = Double(wordStartMs) / 1000.0
                return TranscriptionWord(word: word, startTime: wordStart, endTime: endTime)
            }

            // Refine word end times: each word ends when the next one starts
            var refinedWords = words
            for i in 0..<refinedWords.count {
                if i + 1 < refinedWords.count {
                    refinedWords[i] = TranscriptionWord(
                        word: refinedWords[i].word,
                        startTime: refinedWords[i].startTime,
                        endTime: refinedWords[i + 1].startTime
                    )
                } else {
                    refinedWords[i] = TranscriptionWord(
                        word: refinedWords[i].word,
                        startTime: refinedWords[i].startTime,
                        endTime: endTime
                    )
                }
            }

            return TranscriptionSegment(
                startTime: startTime,
                endTime: endTime,
                text: text,
                words: refinedWords
            )
        }
    }
}

// MARK: - Decodable Types

private struct YouTubePlayerResponse: Decodable {
    let captions: Captions?

    struct Captions: Decodable {
        let playerCaptionsTracklistRenderer: TracklistRenderer?
    }

    struct TracklistRenderer: Decodable {
        let captionTracks: [CaptionTrack]?
    }
}

private struct CaptionTrack: Decodable {
    let baseUrl: String
    let languageCode: String
    let kind: String?
    let name: CaptionTrackName?

    struct CaptionTrackName: Decodable {
        let simpleText: String?
    }
}

private struct YouTubeCaptionJSON3: Decodable {
    let events: [CaptionEvent]?

    struct CaptionEvent: Decodable {
        let tStartMs: Int?
        let dDurationMs: Int?
        let segs: [CaptionSeg]?
    }

    struct CaptionSeg: Decodable {
        let utf8: String?
        let tOffsetMs: Int?
    }
}
