import Foundation
import os

private let logger = Logger(subsystem: "com.summarizecontent.app", category: "YouTubeCaptions")

// MARK: - Public Result

struct YouTubeCaptionResult {
    let segments: [TranscriptionSegment]
    let fullText: String
    let languageCode: String
    let isAutoGenerated: Bool
    let title: String?
    let duration: TimeInterval?
}

// MARK: - Service

struct YouTubeCaptionService {
    private let browserUserAgent =
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"

    // MARK: - Video ID Extraction

    static func extractVideoID(from url: URL) -> String? {
        guard let components = URLComponents(url: url, resolvingAgainstBaseURL: false),
              let host = components.host?.lowercased() else {
            return nil
        }

        // youtu.be/VIDEO_ID
        if host.contains("youtu.be") {
            let path = components.path.trimmingCharacters(in: CharacterSet(charactersIn: "/"))
            return path.isEmpty ? nil : path
        }

        // youtube.com/shorts/VIDEO_ID, /live/VIDEO_ID, /embed/VIDEO_ID
        for segment in ["shorts", "live", "embed"] {
            let parts = components.path.split(separator: "/").map(String.init)
            if let idx = parts.firstIndex(of: segment), idx + 1 < parts.count {
                let id = parts[idx + 1]
                if !id.isEmpty {
                    return id
                }
            }
        }

        // youtube.com/watch?v=VIDEO_ID
        if let vParam = components.queryItems?.first(where: { $0.name == "v" })?.value,
           !vParam.isEmpty {
            return vParam
        }

        return nil
    }

    // MARK: - Fetch Captions

    /// Fetch captions for a YouTube video. Returns nil when no captions are available
    /// (caller should fall back to Whisper).
    func fetchCaptions(from url: URL, preferredLanguage: String = "en") async -> YouTubeCaptionResult? {
        guard let videoID = Self.extractVideoID(from: url) else {
            logger.warning("Could not extract video ID from URL: \(url.absoluteString)")
            return nil
        }

        logger.notice("Fetching captions for video ID: \(videoID)")

        do {
            let watchHTML = try await fetchWatchHTML(from: url)
            let watchTitle = extractWatchTitle(from: watchHTML)

            if let transcriptSegments = try await fetchTranscriptFromEndpoint(
                html: watchHTML,
                originalURL: url
            ), !transcriptSegments.isEmpty {
                let fullText = transcriptSegments.map(\.text).joined(separator: " ")
                let duration = transcriptSegments.map(\.endTime).max()
                logger.notice("Transcript endpoint succeeded with \(transcriptSegments.count) segments")
                return YouTubeCaptionResult(
                    segments: transcriptSegments,
                    fullText: fullText,
                    languageCode: preferredLanguage,
                    isAutoGenerated: false,
                    title: watchTitle,
                    duration: duration
                )
            }

            // Fall back to caption tracks when the transcript endpoint is unavailable.
            let playerResponse = try await fetchPlayerResponse(videoID: videoID, preferredLanguage: preferredLanguage)
            let title = playerResponse.videoDetails?.title?.trimmingCharacters(in: .whitespacesAndNewlines) ?? watchTitle
            let duration = playerResponse.videoDetails?.lengthSeconds.flatMap(TimeInterval.init)
            let renderer = playerResponse.captions?.playerCaptionsTracklistRenderer
            let allTracks = (renderer?.captionTracks ?? []) + (renderer?.automaticCaptions ?? [])
            let orderedTracks = orderedTracks(allTracks, preferredLanguage: preferredLanguage)

            guard !orderedTracks.isEmpty else {
                logger.notice("No caption tracks found for video \(videoID)")
                return nil
            }

            logger.notice("Trying \(orderedTracks.count) caption track candidate(s)")

            for track in orderedTracks {
                logger.notice("Trying caption track: lang=\(track.languageCode), auto=\(track.kind ?? "manual")")
                if let segments = try await downloadTranscript(for: track), !segments.isEmpty {
                    let fullText = segments.map(\.text).joined(separator: " ")
                    let isAuto = track.kind == "asr"
                    logger.notice("Caption track succeeded: \(segments.count) segments, auto=\(isAuto)")
                    return YouTubeCaptionResult(
                        segments: segments,
                        fullText: fullText,
                        languageCode: track.languageCode,
                        isAutoGenerated: isAuto,
                        title: title?.isEmpty == false ? title : nil,
                        duration: duration ?? segments.map(\.endTime).max()
                    )
                }
            }

            logger.notice("All caption track candidates failed for video \(videoID)")
            return nil
        } catch {
            logger.error("Caption fetch failed: \(error.localizedDescription)")
            return nil
        }
    }

    // MARK: - Transcript Endpoint

    private func fetchWatchHTML(from url: URL) async throws -> String {
        var request = URLRequest(url: url)
        request.setValue(browserUserAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("text/html,application/xhtml+xml", forHTTPHeaderField: "Accept")
        request.setValue("en-US,en;q=0.9", forHTTPHeaderField: "Accept-Language")
        request.httpShouldHandleCookies = false
        let (data, _) = try await URLSession.shared.data(for: request)
        return String(data: data, encoding: .utf8) ?? ""
    }

    private func fetchTranscriptFromEndpoint(html: String, originalURL: URL) async throws -> [TranscriptionSegment]? {
        guard let config = extractTranscriptEndpointConfig(from: html) else {
            return nil
        }

        var clientContext = (config.context["client"] as? [String: Any]) ?? [:]
        clientContext["originalUrl"] = originalURL.absoluteString

        var requestContext = config.context
        requestContext["client"] = clientContext

        let body: [String: Any] = [
            "context": requestContext,
            "params": config.params
        ]

        let apiURL = URL(string: "https://www.youtube.com/youtubei/v1/get_transcript?key=\(config.apiKey)")!
        var request = URLRequest(url: apiURL)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.setValue(browserUserAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("https://www.youtube.com", forHTTPHeaderField: "Origin")
        request.setValue(originalURL.absoluteString, forHTTPHeaderField: "Referer")
        request.setValue("0", forHTTPHeaderField: "X-Goog-AuthUser")
        request.setValue("false", forHTTPHeaderField: "X-Youtube-Bootstrap-Logged-In")
        if let clientName = config.clientName {
            request.setValue(clientName, forHTTPHeaderField: "X-Youtube-Client-Name")
        }
        if let clientVersion = config.clientVersion {
            request.setValue(clientVersion, forHTTPHeaderField: "X-Youtube-Client-Version")
        }
        if let visitorData = config.visitorData {
            request.setValue(visitorData, forHTTPHeaderField: "X-Goog-Visitor-Id")
        }
        if let pageCl = config.pageCl {
            request.setValue(String(pageCl), forHTTPHeaderField: "X-Youtube-Page-CL")
        }
        if let pageLabel = config.pageLabel {
            request.setValue(pageLabel, forHTTPHeaderField: "X-Youtube-Page-Label")
        }
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let (data, response) = try await URLSession.shared.data(for: request)
        guard let httpResponse = response as? HTTPURLResponse, (200..<300).contains(httpResponse.statusCode) else {
            return nil
        }

        let sanitizedData = Data(sanitizeYouTubeJSONResponse(data))
        let object = try JSONSerialization.jsonObject(with: sanitizedData)
        return parseTranscriptEndpointSegments(from: object)
    }

    private func extractTranscriptEndpointConfig(from html: String) -> TranscriptEndpointConfig? {
        guard let bootstrap = extractBootstrapConfig(from: html),
              let apiKey = bootstrap["INNERTUBE_API_KEY"] as? String,
              let context = bootstrap["INNERTUBE_CONTEXT"] as? [String: Any],
              let params = firstMatch(in: html, pattern: #""getTranscriptEndpoint":\{"params":"([^"]+)""#) else {
            return nil
        }

        let visitorData = (bootstrap["VISITOR_DATA"] as? String) ?? ((context["client"] as? [String: Any])?["visitorData"] as? String)
        let clientName: String?
        if let raw = bootstrap["INNERTUBE_CONTEXT_CLIENT_NAME"] {
            clientName = "\(raw)"
        } else {
            clientName = nil
        }

        return TranscriptEndpointConfig(
            apiKey: apiKey,
            params: params,
            context: context,
            visitorData: visitorData,
            clientName: clientName,
            clientVersion: bootstrap["INNERTUBE_CONTEXT_CLIENT_VERSION"] as? String,
            pageCl: (bootstrap["PAGE_CL"] as? NSNumber)?.intValue,
            pageLabel: bootstrap["PAGE_BUILD_LABEL"] as? String
        )
    }

    private func extractBootstrapConfig(from html: String) -> [String: Any]? {
        if let objectText = extractBalancedJSONObject(after: "ytcfg.set", in: html),
           let data = objectText.data(using: .utf8),
           let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            return object
        }

        if let objectText = extractBalancedJSONObject(after: "var ytcfg", in: html),
           let data = objectText.data(using: .utf8),
           let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            return object
        }

        return nil
    }

    private func extractBalancedJSONObject(after token: String, in source: String) -> String? {
        guard let tokenRange = source.range(of: token) else { return nil }
        guard let start = source[tokenRange.upperBound...].firstIndex(of: "{") else { return nil }

        var depth = 0
        var inString = false
        var quote: Character?
        var escaping = false
        var index = start

        while index < source.endIndex {
            let char = source[index]

            if inString {
                if escaping {
                    escaping = false
                } else if char == "\\" {
                    escaping = true
                } else if char == quote {
                    inString = false
                    quote = nil
                }
            } else {
                if char == "\"" || char == "'" {
                    inString = true
                    quote = char
                } else if char == "{" {
                    depth += 1
                } else if char == "}" {
                    depth -= 1
                    if depth == 0 {
                        return String(source[start...index])
                    }
                }
            }

            index = source.index(after: index)
        }

        return nil
    }

    private func sanitizeYouTubeJSONResponse(_ data: Data) -> [UInt8] {
        let prefix = Array(")]}'".utf8)
        let bytes = Array(data)
        if bytes.starts(with: prefix) {
            return Array(bytes.dropFirst(prefix.count))
        }
        return bytes
    }

    private func parseTranscriptEndpointSegments(from object: Any) -> [TranscriptionSegment]? {
        guard let root = object as? [String: Any],
              let actions = root["actions"] as? [[String: Any]],
              let updatePanel = actions.first?["updateEngagementPanelAction"] as? [String: Any],
              let content = updatePanel["content"] as? [String: Any],
              let transcriptRenderer = content["transcriptRenderer"] as? [String: Any],
              let rendererContent = transcriptRenderer["content"] as? [String: Any],
              let searchPanel = rendererContent["transcriptSearchPanelRenderer"] as? [String: Any],
              let body = searchPanel["body"] as? [String: Any],
              let segmentListRenderer = body["transcriptSegmentListRenderer"] as? [String: Any],
              let initialSegments = segmentListRenderer["initialSegments"] as? [[String: Any]] else {
            return nil
        }

        let segments: [TranscriptionSegment] = initialSegments.compactMap { segment in
            guard let renderer = segment["transcriptSegmentRenderer"] as? [String: Any],
                  let snippet = renderer["snippet"] as? [String: Any],
                  let runs = snippet["runs"] as? [[String: Any]] else {
                return nil
            }

            let text = runs.compactMap { $0["text"] as? String }.joined().trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { return nil }

            let startMs = Self.intValue(renderer["startMs"]) ?? 0
            let durationMs = Self.intValue(renderer["durationMs"])
            let startTime = Double(startMs) / 1000.0
            let endTime = Double(startMs + (durationMs ?? 0)) / 1000.0

            return TranscriptionSegment(
                startTime: startTime,
                endTime: max(endTime, startTime),
                text: text
            )
        }

        return segments.isEmpty ? nil : segments
    }

    // MARK: - Innertube API

    /// Fetch caption tracks using YouTube's innertube player API.
    /// This returns the player response directly as JSON — no HTML parsing needed.
    private func fetchPlayerResponse(videoID: String, preferredLanguage: String) async throws -> YouTubePlayerResponse {
        let webResponse = try await requestPlayerResponse(
            videoID: videoID,
            clientName: "WEB",
            clientVersion: "2.20250101.00.00",
            preferredLanguage: preferredLanguage
        )

        let webTracks = (webResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [])
            + (webResponse.captions?.playerCaptionsTracklistRenderer?.automaticCaptions ?? [])
        if !webTracks.isEmpty {
            return webResponse
        }

        return try await requestPlayerResponse(
            videoID: videoID,
            clientName: "ANDROID",
            clientVersion: "20.10.38",
            preferredLanguage: preferredLanguage
        )
    }

    private func requestPlayerResponse(
        videoID: String,
        clientName: String,
        clientVersion: String,
        preferredLanguage: String
    ) async throws -> YouTubePlayerResponse {
        let apiURL = URL(string: "https://www.youtube.com/youtubei/v1/player?prettyPrint=false")!

        var request = URLRequest(url: apiURL)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.setValue(browserUserAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("https://www.youtube.com", forHTTPHeaderField: "Origin")
        request.setValue("https://www.youtube.com/", forHTTPHeaderField: "Referer")

        let body: [String: Any] = [
            "videoId": videoID,
            "context": [
                "client": [
                    "clientName": clientName,
                    "clientVersion": clientVersion,
                    "hl": preferredLanguage
                ]
            ]
        ]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let (data, response) = try await URLSession.shared.data(for: request)

        if let httpResponse = response as? HTTPURLResponse {
            logger.notice("Innertube API response status: \(httpResponse.statusCode)")
        }

        let sanitizedData = Data(sanitizeYouTubeJSONResponse(data))
        return try JSONDecoder().decode(YouTubePlayerResponse.self, from: sanitizedData)
    }

    // MARK: - Track Selection

    /// Sort caption tracks: manual before auto-generated, then prefer the requested language.
    private func orderedTracks(_ tracks: [CaptionTrack], preferredLanguage: String) -> [CaptionTrack] {
        tracks.sorted { lhs, rhs in
            let lhsAuto = lhs.kind == "asr"
            let rhsAuto = rhs.kind == "asr"
            if lhsAuto != rhsAuto {
                return rhsAuto
            }

            let lhsPreferred = lhs.languageCode == preferredLanguage || lhs.languageCode.hasPrefix("\(preferredLanguage)-")
            let rhsPreferred = rhs.languageCode == preferredLanguage || rhs.languageCode.hasPrefix("\(preferredLanguage)-")
            if lhsPreferred != rhsPreferred {
                return lhsPreferred
            }

            let lhsEnglish = lhs.languageCode == "en" || lhs.languageCode.hasPrefix("en-")
            let rhsEnglish = rhs.languageCode == "en" || rhs.languageCode.hasPrefix("en-")
            if lhsEnglish != rhsEnglish {
                return lhsEnglish
            }

            return lhs.languageCode < rhs.languageCode
        }
    }

    private func downloadTranscript(for track: CaptionTrack) async throws -> [TranscriptionSegment]? {
        guard let json3URL = trackDownloadURL(from: track.baseUrl, format: "json3", altJSON: true) else {
            return nil
        }

        var request = URLRequest(url: json3URL)
        request.setValue(browserUserAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("en-US,en;q=0.9", forHTTPHeaderField: "Accept-Language")

        if let (data, response) = try? await URLSession.shared.data(for: request),
           let httpResponse = response as? HTTPURLResponse,
           (200..<300).contains(httpResponse.statusCode) {
            if let json3 = try? JSONDecoder().decode(YouTubeCaptionJSON3.self, from: data) {
                let segments = convertToSegments(json3)
                if !segments.isEmpty {
                    return segments
                }
            }

            if let raw = String(data: data, encoding: .utf8) {
                let xmlSegments = parseXMLTranscript(raw)
                if !xmlSegments.isEmpty {
                    return xmlSegments
                }
            }
        }

        guard let xmlURL = trackDownloadURL(from: track.baseUrl, format: nil, altJSON: false) else {
            return nil
        }

        var xmlRequest = URLRequest(url: xmlURL)
        xmlRequest.setValue(browserUserAgent, forHTTPHeaderField: "User-Agent")
        xmlRequest.setValue("en-US,en;q=0.9", forHTTPHeaderField: "Accept-Language")
        let (data, response) = try await URLSession.shared.data(for: xmlRequest)
        guard let httpResponse = response as? HTTPURLResponse, (200..<300).contains(httpResponse.statusCode),
              let raw = String(data: data, encoding: .utf8) else {
            return nil
        }

        let xmlSegments = parseXMLTranscript(raw)
        return xmlSegments.isEmpty ? nil : xmlSegments
    }

    private func trackDownloadURL(from baseURL: String, format: String?, altJSON: Bool) -> URL? {
        guard var components = URLComponents(string: baseURL) else { return URL(string: baseURL) }

        var queryItems = components.queryItems ?? []
        queryItems.removeAll { $0.name == "fmt" || $0.name == "alt" }

        if let format {
            queryItems.append(URLQueryItem(name: "fmt", value: format))
        }
        if altJSON {
            queryItems.append(URLQueryItem(name: "alt", value: "json"))
        }

        components.queryItems = queryItems.isEmpty ? nil : queryItems
        return components.url
    }

    private func parseXMLTranscript(_ xml: String) -> [TranscriptionSegment] {
        guard let regex = try? NSRegularExpression(pattern: #"<text\b([^>]*)>([\s\S]*?)</text>"#) else {
            return []
        }

        let nsrange = NSRange(xml.startIndex..., in: xml)
        return regex.matches(in: xml, range: nsrange).compactMap { match in
            guard let attributesRange = Range(match.range(at: 1), in: xml),
                  let contentRange = Range(match.range(at: 2), in: xml) else {
                return nil
            }

            let attributes = String(xml[attributesRange])
            let text = decodeHTMLEntities(String(xml[contentRange]))
                .replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { return nil }

            let startSeconds = firstMatch(in: attributes, pattern: #"start\s*=\s*['"]([^'"]+)['"]"#).flatMap(Double.init) ?? 0
            let durationSeconds = firstMatch(in: attributes, pattern: #"dur\s*=\s*['"]([^'"]+)['"]"#).flatMap(Double.init) ?? 0

            return TranscriptionSegment(
                startTime: startSeconds,
                endTime: max(startSeconds + durationSeconds, startSeconds),
                text: text
            )
        }
    }

    private func extractWatchTitle(from html: String) -> String? {
        guard let title = firstMatch(in: html, pattern: #"<title>(.*?)</title>"#) else { return nil }
        let decoded = decodeHTMLEntities(title)
            .replacingOccurrences(of: " - YouTube", with: "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return decoded.isEmpty ? nil : decoded
    }

    private func decodeHTMLEntities(_ input: String) -> String {
        input
            .replacingOccurrences(of: "&amp;", with: "&")
            .replacingOccurrences(of: "&lt;", with: "<")
            .replacingOccurrences(of: "&gt;", with: ">")
            .replacingOccurrences(of: "&quot;", with: "\"")
            .replacingOccurrences(of: "&#39;", with: "'")
            .replacingOccurrences(of: "&#x27;", with: "'")
            .replacingOccurrences(of: "&nbsp;", with: " ")
    }

    private func firstMatch(in string: String, pattern: String) -> String? {
        guard let regex = try? NSRegularExpression(pattern: pattern, options: [.caseInsensitive]) else {
            return nil
        }
        let range = NSRange(string.startIndex..., in: string)
        guard let match = regex.firstMatch(in: string, range: range),
              let captureRange = Range(match.range(at: 1), in: string) else {
            return nil
        }
        return String(string[captureRange])
    }

    private static func intValue(_ value: Any?) -> Int? {
        switch value {
        case let int as Int:
            return int
        case let string as String:
            return Int(string)
        case let number as NSNumber:
            return number.intValue
        default:
            return nil
        }
    }

    // MARK: - JSON3 → TranscriptionSegment

    /// Convert JSON3 events into `TranscriptionSegment` array.
    private func convertToSegments(_ json3: YouTubeCaptionJSON3) -> [TranscriptionSegment] {
        guard let events = json3.events else { return [] }

        // Filter to events that have segment data (segs array)
        let captionEvents = events.filter { $0.segs != nil && !($0.segs?.isEmpty ?? true) }

        return captionEvents.compactMap { event in
            guard let segs = event.segs else { return nil }

            let startMs = event.tStartMs ?? 0
            let durationMs = event.dDurationMs ?? 0
            let startTime = Double(startMs) / 1000.0
            let endTime = Double(startMs + durationMs) / 1000.0

            // Build text from segments
            let text = segs.map { $0.utf8 ?? "" }.joined().trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { return nil }

            // Build word-level timing when offset data is available
            let words: [TranscriptionWord] = segs.compactMap { seg in
                guard let word = seg.utf8?.trimmingCharacters(in: .whitespacesAndNewlines),
                      !word.isEmpty else { return nil }

                let wordStartMs = startMs + (seg.tOffsetMs ?? 0)
                let wordStart = Double(wordStartMs) / 1000.0
                return TranscriptionWord(word: word, startTime: wordStart, endTime: endTime)
            }

            // Refine word end times: each word ends when the next one starts
            var refinedWords = words
            for i in 0..<refinedWords.count {
                if i + 1 < refinedWords.count {
                    refinedWords[i] = TranscriptionWord(
                        word: refinedWords[i].word,
                        startTime: refinedWords[i].startTime,
                        endTime: refinedWords[i + 1].startTime
                    )
                } else {
                    refinedWords[i] = TranscriptionWord(
                        word: refinedWords[i].word,
                        startTime: refinedWords[i].startTime,
                        endTime: endTime
                    )
                }
            }

            return TranscriptionSegment(
                startTime: startTime,
                endTime: endTime,
                text: text,
                words: refinedWords
            )
        }
    }
}

// MARK: - Decodable Types

private struct TranscriptEndpointConfig {
    let apiKey: String
    let params: String
    let context: [String: Any]
    let visitorData: String?
    let clientName: String?
    let clientVersion: String?
    let pageCl: Int?
    let pageLabel: String?
}

private struct YouTubePlayerResponse: Decodable {
    let captions: Captions?
    let videoDetails: VideoDetails?

    struct Captions: Decodable {
        let playerCaptionsTracklistRenderer: TracklistRenderer?
    }

    struct TracklistRenderer: Decodable {
        let captionTracks: [CaptionTrack]?
        let automaticCaptions: [CaptionTrack]?
    }

    struct VideoDetails: Decodable {
        let title: String?
        let lengthSeconds: String?
    }
}

private struct CaptionTrack: Decodable {
    let baseUrl: String
    let languageCode: String
    let kind: String?
    let name: CaptionTrackName?

    struct CaptionTrackName: Decodable {
        let simpleText: String?
    }
}

private struct YouTubeCaptionJSON3: Decodable {
    let events: [CaptionEvent]?

    struct CaptionEvent: Decodable {
        let tStartMs: Int?
        let dDurationMs: Int?
        let segs: [CaptionSeg]?
    }

    struct CaptionSeg: Decodable {
        let utf8: String?
        let tOffsetMs: Int?
    }
}
